### PR TITLE
MagTag fixes

### PR DESCRIPTION
**Pull request by bcr**
Some changes to handle issues I found with the MagTag:

1. Unknown board ID. I don't know if @FoamyGuy has a bigger plan to manage this. I added it by hand to the JSON file.
2. If there is no stable firmware version (there isn't for the MagTag), the update would explode. Now it complains. Then explodes.

### CODE REVIEW

**Comment by FoamyGuy** [comment]
I get this error. Does your board have a different name string than mine?

```
❯ blinka update
Traceback (most recent call last):
  File "/home/timc/.local/bin/blinka", line 33, in <module>
    sys.exit(load_entry_point('blinka-bcr', 'console_scripts', 'blinka')())
  File "/home/timc/repos/circuitpython/blinka-cli_bcr/blinka/__main__.py", line 5, in main
    return blinka.blinka.main()
  File "/home/timc/repos/circuitpython/blinka-cli_bcr/blinka/blinka.py", line 62, in main
    options.func(options)
  File "/home/timc/repos/circuitpython/blinka-cli_bcr/blinka/commands/update.py", line 36, in do_update
    (version, board_id) = blinka.board.identify(args.root)
  File "/home/timc/repos/circuitpython/blinka-cli_bcr/blinka/board.py", line 30, in identify
    return (version, boards[boot_board])
KeyError: 'Adafruit MagTag with ESP32S2'
```

**Comment by bcr** [comment]
It appears your board identifies as `Adafruit MagTag with ESP32S2` and mine as `MagTag with ESP32S2`. I'll add a more helpful message in this case.

**Comment by FoamyGuy** [comment]
I wonder if it's a version thing. I am on something newer than the unstable release even. I'll back track a bit and see if it changes.

**Comment by bcr** [comment]
```
➜  ~ cat /media/blake/CIRCUITPY/boot_out.txt 
Adafruit CircuitPython 6.1.0-beta.2 on 2020-12-03; MagTag with ESP32S2
```
Is my full boot_out.txt

**Comment by FoamyGuy** [comment]
Yep that is the deal... The name is changed in one of the versions newer than the current unstable. Whenever the next release is made the new name (with Adafruit) will be more widespread after a while.

**Comment by bcr** [comment]
Yeah, I think the general problem is we need to treat the namespaces with some respect. I think right now we need to bear the pain of including every  prior version of the name.

This of course is impacting the firmware filenames also:

```
➜  ~ ls -alh ~/Downloads/*.uf2
-rw-rw-r-- 1 blake blake 2.4M Dec 26 17:07 /home/blake/Downloads/adafruit-circuitpython-adafruit_magtag_2.9_grayscale-en_US-6.1.0-beta.2.uf2
```
We got enough "adafruit" in there? (yes I know the first "adafruit" is referring to "adafruit is your friend behind CircuitPython" and the second "adafruit" is "did I mention the MagTag board is by Adafruit?")

Also I fixed the unknown board handling a little better:

```
➜  ~ blinka update       
🤬 Could not automatically determine your board type, use the --board option
```

**Review by FoamyGuy — APPROVED** [review]
I like the unknown board handling. This looks good to me. I'll keep an eye on the restart into bootloader issue for ESP32-S2 based devices.

**Pull request merged**
