### PR TITLE
adding atmel boards

### PR DESCRIPTION
**Pull request by FoamyGuy**
This adds many other atmel boards. 

I generated this list using a script like this in the `ports/atmel-samd/` dir inside circuitpython repo. 
```python
import os

for device_dir in os.listdir("boards"):
    if "." not in device_dir:
        f = open("boards/{}/mpconfigboard.h".format(device_dir))
        first_6_lines = f.read().split("\n")[:6]
        f.close()
        device_name = None
        mcu_name = None
        #print("working {}".format(device_dir))
        for line in first_6_lines:
            if "MICROPY_HW_BOARD_NAME" in line:
                device_name = line.replace("#define MICROPY_HW_BOARD_NAME ","").replace('"', "")
                #print(device_name)
            if "MICROPY_HW_MCU_NAME" in line:
                mcu_name = line.split(" ")[2].replace('"', "")

        #print("{} with {}".format(device_name, mcu_name))
        bout_out_name = "{} with {}".format(device_name, mcu_name)
        print('"{}": "{}",'.format(bout_out_name, device_dir))
```

I have not tested all of these. The two that you had done by hand matched perfectly the ones that were outputted by my script. I'll test on a handful of devices that I have access to today.

One potential issue is that this device seems to have two variants that both have the exact same `boot_out.txt` value so we would n't be able to distinguish them. 
```
    #"SparkFun Qwiic Micro with samd21e18": "sparkfun_qwiic_micro_no_flash",
    #"SparkFun Qwiic Micro with samd21e18": "sparkfun_qwiic_micro_with_flash",
```

### CODE REVIEW

**Comment by FoamyGuy** [comment]
I've also added some more of the expected boot drive names as well. These were generated using this script:
```python
import os
boot_names = []
for dir in os.listdir("boards"):
    f = open("boards/{}/board_config.h".format(dir), "r")
    config_file_contents = f.read()
    f.close()
    for line in config_file_contents.split("\n"):
        if line.startswith("#define VOLUME_LABEL "):
            boot_name = line.replace("#define VOLUME_LABEL ", "").replace('"', "")
            if boot_name not in boot_names:
                boot_names.append(boot_name)
            break

print(boot_names)
```
inside of the root of this repo: https://github.com/adafruit/uf2-samdx1 

There are similar repos for the other main chips bootloaders as well that could be imported similarly.

**Comment by bcr** [comment]
As for the collision in the namespaces, I intended the `--board` option to help with that if needed. But yeah, this is probably something worthy of a broader philosophical conversation with the CircuitPython team.

**Comment by bcr** [comment]
In general this needs to be a bit more maintainable. That is, we should probably put all of this junk in a completely separate downloadable file instead of putting it in the code. That way you don't have to update the utility every time there's a change.

**Comment by bcr** [comment]
The board change in PR #2 caused a conflict, do you mind fixing it for me? I am going to test the other code on Windows right now.

**Comment by FoamyGuy** [comment]
> In general this needs to be a bit more maintainable. That is, we should probably put all of this junk in a completely separate downloadable file instead of putting it in the code. That way you don't have to update the utility every time there's a change.

Agree'd. What do you think about keeping it in a JSON file that we can load from? 

Maybe down the line we can incorporate the scripts that generate those lists into this project as well so it will have an easy way to update.

**Comment by bcr** [comment]
> Agree'd. What do you think about keeping it in a JSON file that we can load from?
> 
> Maybe down the line we can incorporate the scripts that generate those lists into this project as well so it will have an easy way to update.

Amen. I think that a supporting scripts folder is perfectly reasonable and warranted, starting with the snippets you already did.

**Pull request merged**
