### PR TITLE
Packaging refactor

### LINKED ISSUE #9: Make a top-level Blinka command and installable package
People should be able to install this with an unsurprising mechanism like `pip3 install blinka`

I'd like it so that maintainers can have a "live" version of blinka as they work on the code. Which I think is accomplished with https://stackoverflow.com/questions/42609943/what-is-the-use-case-for-pip-install-e

### PR DESCRIPTION
**Pull request by bcr**
I am trying to straighten out the package structure to make this installable. Note the way I changed the resource loading -- works on Pop_OS in my testing. Resolves #9

### CODE REVIEW

**Comment by bcr** [comment]
This works on my Pop!_OS. I can do a `pip install -e .` and magic happens to make a top-level `blinka` command.

**Comment by bcr** [comment]
Also, `python -m blinka` should work also

**Review by FoamyGuy — APPROVED** [review]
Looks good to me. I successfully tested `pip install -e .` and then using `blinka` from different directories. I also tested `python -m blinka` 

I never knew how pip entry point magic worked, this is neat!

**Comment by bcr** [comment]
Yeah, this PR will be instructive for Future Blake when he needs to remember how Python packaging works. Fun stuff.

**Pull request merged**
